version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: docs/
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

# Build documentation from the docs/ directory
# This tells ReadTheDocs to look for Docusaurus configuration
# in the docs/ subdirectory
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Install dependencies from the docs/ directory
python:
  install:
    - method: pip
      path: docs/
      extra_requirements:
        - docs

# Since we're using Docusaurus, we don't need Sphinx configuration
# But ReadTheDocs expects this field
sphinx:
  configuration: docs/conf.py

# Enable PDF and EPUB output formats
formats:
  - pdf
  - epub

# Additional build options
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create:
      - echo "Building JCacheX documentation with Docusaurus"
      - cd docs
      - npm install
      - npm run build

# Environment variables
environment:
  NODE_VERSION: "18"
  NPM_VERSION: "9"

# Build commands for Docusaurus
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create:
      - echo "Setting up Node.js environment"
      - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - node --version
      - npm --version
      - echo "Installing Docusaurus dependencies"
      - cd docs
      - npm install
      - echo "Building documentation"
      - npm run build
      - echo "Build completed successfully"
