apiVersion: v1
kind: ServiceAccount
metadata:
  name: jcachex-service-account
  namespace: jcachex-demo
  labels:
    app: jcachex

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jcachex-cluster-role
  labels:
    app: jcachex
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jcachex-cluster-role-binding
  labels:
    app: jcachex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jcachex-cluster-role
subjects:
- kind: ServiceAccount
  name: jcachex-service-account
  namespace: jcachex-demo
